fix: Service実装
takurouishihara/raisetech-task9 pull request #3
Opened 2022-11-14 13:55 UTC by takurouishihara

色々ありましたが、ようやくServiceの実装でつくようになりました。
（`MovieMapper`のageがidと間違っていたみたいで、ageがidと同じ値になっていたようです。ようやく解決しました。）
次は、
`localhost:8080/movies?movie_database=1989` にアクセスするとDBに登録されている映画から1989年に
公開された映画をレスポンスとして返すようにします。
例） 
```
  {
        "name": "となりのトトロ",
        "age": 1989
    },
```
![image](https://user-images.githubusercontent.com/112872918/201676256-5232fdd6-f646-4e3f-9fd0-56eee11f82b4.png)

2022-11-15 01:26 UTC, takurouishihara commented
![image](https://user-images.githubusercontent.com/112872918/201803694-c7b00b23-e97e-45e9-9618-57156b2c7206.png)

2022-11-15 02:42 UTC, YudaiNoda3576 requested changes
コメントしています！

2022-11-15 02:42 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/raisetechtask9/controller/MovieController.java
> +    public List<MovieResponse> getAge(@RequestParam("age") Integer age) {
ここのメソッドは年代で映画を取得することだと思うので命名に違和感があります！

2022-11-15 02:42 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/raisetechtask9/controller/MovieResponse.java
> +    public void setName(String name) {
Class単位でSetterを生成してますが、ここで再度setterを定義する必要はありそうですか？
また、setterはどこで使用されていますか？？

2022-11-15 02:42 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/raisetechtask9/entity/Movie.java
>      private  String name;
空白が一個多いのが気になります！

2022-11-15 02:42 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/raisetechtask9/entity/Movie.java
>          return name;
コンストラクタが特定のフィールドの値を返却する挙動に違和感があります。。。

2022-11-15 02:42 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/raisetechtask9/entity/Movie.java
> +
ここでLombokを利用していない理由って何かありますか？？

2022-11-15 02:42 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/raisetechtask9/service/MovieServiceImpl.java
> +        return movieMapper.findById(id);
例外処理なども実装のほどよろしくお願いします🙏
L.29も同様

2022-11-15 03:06 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/controller/MovieResponse.java
> +    public void setName(String name) {
```
変更するのが setter
取得するのが getter
```
とのことだったので、READ処理では使わないですね。修正します。

2022-11-15 03:38 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/controller/MovieResponse.java
> +    public void setName(String name) {
```
変更するのが setter
取得するのが getter
```
と分かりました。まだ取得しかしていないのにsetterは使わないですね。修正します。

2022-11-15 03:48 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/entity/Movie.java
> +
Lombokを追加します。
`Lombokは言語仕様上省く事ができない定型的なコードの事である。 `
と調べると出てくるので、まだなれませんが
```
    private int id;
    private  String name;
    private Integer age;
```
のような何度も使うものがあった際は使うようにしていきます。

2022-11-15 03:49 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/service/MovieServiceImpl.java
> +        return movieMapper.findById(id);
これから、実装します！

2022-11-15 03:51 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/controller/MovieController.java
> +    public List<MovieResponse> getAge(@RequestParam("age") Integer age) {
MovieResponseのほかにAgeResponseを追加し、そちらで動くようにします。

2022-11-15 03:54 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/entity/Movie.java
>          return name;
nemeを返すものは、使わないためということでしょうか？

2022-11-15 04:10 UTC, takurouishihara reviewed
先ほどご指摘されたLombok等の修正をしましたので、確認よろしくお願いします。

2022-11-15 04:10 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/controller/AgeResponse.java
> +}
命名が紛らわしいとのご指摘がありましたので、MovieResponseとは別にAgeResponseを作りました。

2022-11-15 11:38 UTC, TomooAkamatsu commented on src/main/java/net/raisetech/raisetechtask9/controller/MovieController.java
>      public MovieController(MovieService movieService) {
コンストラクタインジェクションもlombokを利用してもっと簡潔に書くことができますので、よければ調べてみて下さい！

2022-11-15 11:41 UTC, TomooAkamatsu commented on src/main/java/net/raisetech/raisetechtask9/controller/AgeResponse.java
> +}
横からすみません
おそらくですが、ゆーだいさんがご指摘されたのは、映画の公開年はageではなくyearの方が適切なのでは、ということかなと思いました

2022-11-15 11:44 UTC, TomooAkamatsu commented
各ファイル、行末に改行を入れましょう！

IDEの設定でセーブ時に自動で改行してくれる設定があります。
なぜそうするのかも合わせて、調べてみて下さい！

2022-11-16 23:38 UTC, takurouishihara reviewed
　野田さんにご指摘された「年代で映画を取得することだと思うので命名に違和感があります」を解決しようとし、変更後Dockerを再起動したところ、不具合が出たので原因がどこなのか助言をお願いします。

2022-11-16 23:38 UTC, takurouishihara commented on sql/001-create-table-and-load-data.sql
> +INSERT INTO movies (id, name,published_Year) VALUES (1, "風の谷のナウシカ",1984);
ageから、published_Yearに変更後、Dockerを再起動したところ、写真の様にテーブルまでは大丈夫なのですが、その後のselect * from movies;と打っても何も出ないという状態に陥りました。published_Yearが長すぎるのが原因でしょうか？
 　Dockerの手順としては、
% docker compose down
% docker system prune -a
% docker system prune --volumes
% docker network prune 
で一度残ったデータを完全に消してから
% docker compose　up
% docker compose exec db mysql -uroot -p
･･･
と、続けていきました。原因がなにか分からないので助言をお願いします。
![image](https://user-images.githubusercontent.com/112872918/202317610-5961cde6-c198-46bb-ba68-1e54f76360f1.png)

2022-11-17 05:39 UTC, takurouishihara reviewed
例外処理の追加をしました。

2022-11-17 05:39 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/service/MovieServiceImpl.java
> +        return Optional.ofNullable(movieMapper.findByPublished_year(published_year).orElseThrow(() -> new ResourceNotFoundException("resource not found")));
例外処理の追加をしました。
成功したときの戻り値
![image](https://user-images.githubusercontent.com/112872918/202365094-2d9488cd-2270-4696-b280-5ddd1af63d8e.png)
例外処理発生時
![image](https://user-images.githubusercontent.com/112872918/202365310-6b7e7ea2-2915-4550-851a-3f01c8435770.png)

2022-11-17 12:14 UTC, takurouishihara reviewed
　POSTを追加しようとしたのですが、うまくいかなかったためまた、助言をお願いします。
そして、例外処理はこのやり方で合っていますでしょうか？

2022-11-17 12:26 UTC, takurouishihara reviewed
　POSTを追加しようとしたのですが、上手くいかないため、アドバイスをお願いします。
そして、例外処理はこのやり方で合っていますでしょうか？

2022-11-17 12:26 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/controller/MovieController.java
> +    @PostMapping("movies")
　POST処理の追加をしたのですが、写真のように405のerrorになり、表示がされません。405になる理由として、
①アクセスをリクエストしたページが存在しない場合
②ページが存在しているにもかかわらず、アクセスを拒否されている状態
の2つがあるそうですが、今回は②が関係しているのでしょうか。助言をお願いします。
POST処理の現状
![image](https://user-images.githubusercontent.com/112872918/202445530-969759b3-1733-419d-a4ae-fc9569ea4c5e.png)

2022-11-18 09:39 UTC, takurouishihara reviewed
一端POST処理を削って、公開年度をクエリ文字列で取得出来るようにしました。
小山先生のおっしゃっていた様に行かなかったのですが、もし間違いであればご指摘ください。

2022-11-18 09:39 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/controller/MovieController.java
> -      }
一端POST処理に関するものを取り除きました。

2022-11-18 09:39 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/controller/MovieController.java
> -    @GetMapping("/{published_year}")
`①/movies?published_year=1996` で該当の年に公開された映画を検索するAPIの実装
とおっしゃっていたのですが、上手くいかず、
`/published_year?published_year=1986`
だと付くので、こちらでもよろしいでしょうか？


`/published_year?published_year=1986`の場合
![image](https://user-images.githubusercontent.com/112872918/202668171-1e0248c9-d6b5-47ff-a25f-cbb8235a9ee3.png)

`/movies?published_year=1996 `だと、findAllの時と同様の結果になる。
![image](https://user-images.githubusercontent.com/112872918/202668419-7f0333b5-794b-4c31-8ce8-d67e04b7fac4.png)

2022-11-18 13:27 UTC, takurouishihara reviewed
全件検索だとpostmanで表示できますが、`/movies?published_year=1986`のような値があれば公開年検索で500のerrorになります。
```
if (published_year.isEmpty()) {
}
```
で公開年が空なら･･･
```
 } else {
}
```
で、値があった場合の処理だと思ったのですが、どこが原因でしょうか？

2022-11-18 13:27 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/controller/MovieController.java
この`@GetMapping("/movies")`を一つにまとめようとしています。
　`公開年がnullならば全件検索、何か値があれば公開年で検索`を目標としていますが、現状は`公開年がnullならば全件検索`は無事つくようになりました。が、`何か値があれば公開年で検索`という部分でステータスが500のerrorが起きています。

2022-11-20 04:15 UTC, takurouishihara reviewed
第9回課題について、お願いします。
　動画のように、 Optionalをなるべく引数に含めないように変更しました。また、マージする前にこれも変更した方が･･･という点がありましたら、教えて頂けますでしょうか。

2022-11-20 04:15 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/service/MovieService.java
> +    List<Movie> findByPublished_year(Integer publishedYear);
このような、引数の中に、Optionalをなるべく使わないように今後、気をつけます。

2022-11-20 04:15 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/service/MovieServiceImpl.java
> -        return Optional.ofNullable(movieMapper.findByPublished_year(publishedYear).orElseThrow(() -> new ResourceNotFoundException("resource not found")));
この、 findByPublished_yearに、例外処理をしていましたが、（/moives）の統一により、使わなくなったため、idの方に例外を付けようと思っているのですが、よろしいでしょうか？もし、それで大丈夫なのなら、それが終わり次第マージしようと思います。この他にもマージする前に治した方が良いことがありましたら、お願いします。

2022-11-20 05:02 UTC, yoshi-koyama commented on build.gradle
> +    runtimeOnly 'com.mysql:mysql-connector-j'
フォーマットが気になります。
それから`org.jetbrains:annotations`はいらないはず。

2022-11-20 05:02 UTC, yoshi-koyama commented on sql/001-create-table-and-load-data.sql
> +INSERT INTO movies (id, name,published_year) VALUES (1, "風の谷のナウシカ",1984);
半角スペースを入れましょう。
```suggestion
INSERT INTO movies (id, name, published_year) VALUES (1, "風の谷のナウシカ",1984);
```

2022-11-20 05:02 UTC, yoshi-koyama commented on src/main/java/net/raisetech/raisetechtask9/mapper/MovieMapper.java
> +    List<Movie> findByPublished_year(Integer publishedYear);
メソッド名についてJavaの命名規則に従って直しましょう。

2022-11-20 05:02 UTC, yoshi-koyama commented on src/main/resources/application.properties
> +localUrl = http://localhost:8080
これ、いらないのでは？

2022-11-20 05:02 UTC, yoshi-koyama commented on src/main/java/net/raisetech/raisetechtask9/mapper/MovieMapper.java
> +    boolean isPresent();
これは要らないはず。

2022-11-20 07:35 UTC, takurouishihara reviewed
ご指摘された箇所の修正をしました。また、フォーマットの件で解釈が正しいのか分からないため教えて頂けますでしょうか。

2022-11-20 07:35 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/controller/MovieController.java
> +        return Optional.ofNullable(movieService.findById(id).orElseThrow(() -> new ResourceNotFoundException("resource not found")));
ここに、例外処理を追加しました。
正常
![image](https://user-images.githubusercontent.com/112872918/202890179-175ecca3-7393-48a8-90a3-8f77f2d1bfab.png)
例外発生時
![image](https://user-images.githubusercontent.com/112872918/202890191-4ebfdb5c-e7c1-4be1-99b4-9a12c466c2b3.png)

2022-11-20 07:35 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/controller/MovieController.java
> +            return movieService.findByPublishedYear(publishedYear.get()).stream().map(MovieResponse::new).toList();
camelCase記法
- 先頭を小文字
- 以降も小文字
- **_言葉の区切りは大文字_**
- 予約語ではない英単語と略語を組み合わせることが多い
とのことなので、スネークケースから変更しました。
とのことなので、

2022-11-20 07:35 UTC, takurouishihara commented on src/main/resources/application.properties
> -localUrl = http://localhost:8080
いつ追加したのか不明ですが消しました。以後気をつけます。

2022-11-20 07:35 UTC, takurouishihara commented on build.gradle
>      runtimeOnly 'com.mysql:mysql-connector-j'
` runtimeOnly 'com.mysql:mysql-connector-j'`
　のフォーマットの件ですが、
` runtimeMultiple'com.mysql:mysql-connector-j`　
　のように変更するという解釈でよろしいでしょうか？これで試してみてだめだったので、調べてみたのですが分からなかったです。
　そもそもフォーマットって「特定のルールに則って書かれた文章。」という意味らしいのですが、どういう風に変更しても大丈夫なのですか？

2022-11-20 09:20 UTC, yoshi-koyama commented on build.gradle
>      runtimeOnly 'com.mysql:mysql-connector-j'
いえ！
```
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.2.2'
    runtimeOnly 'com.mysql:mysql-connector-j'
```
となっているのを
```
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.2.2'
	runtimeOnly 'com.mysql:mysql-connector-j'
```
のようにインデントを合わせてほしいという意味で申し上げております 🙇

2022-11-20 09:22 UTC, yoshi-koyama reviewed
コメントしました！
あと少しかと思います！！

2022-11-20 09:22 UTC, yoshi-koyama commented on src/main/java/net/raisetech/raisetechtask9/controller/MovieController.java
> +    public Optional<Movie> getMovieId(@PathVariable("id") int id) {
下記のほうがメソッド名としてよいかと思います。
```suggestion
    public Optional<Movie> getMovieById(@PathVariable("id") int id) {
```
または
```suggestion
    public Optional<Movie> getById(@PathVariable("id") int id) {
```

2022-11-20 09:22 UTC, yoshi-koyama commented on src/main/java/net/raisetech/raisetechtask9/controller/MovieController.java
> +        return Optional.ofNullable(movieService.findById(id).orElseThrow(() -> new ResourceNotFoundException("resource not found")));
ありがとうございます！
できたら例外をthrowするかどうかの判定は業務ロジックと捉えてServiceImplで実装してほしいです。
Controllerでは例外をthrowするかどうかなどのロジックをなるだけもちたくないです。

2022-11-20 09:22 UTC, yoshi-koyama commented on src/main/java/net/raisetech/raisetechtask9/controller/MovieResponse.java
> +    private Integer published_year;
こちらも下記のようにしてほしいです！
```suggestion
    private Integer publishedYear;
```

2022-11-21 00:03 UTC, takurouishihara reviewed
ご指摘された箇所を修正しました。ご確認よろしくお願いします。

2022-11-21 00:03 UTC, takurouishihara commented on build.gradle
>      runtimeOnly 'com.mysql:mysql-connector-j'
そういうことだったのですね。分かりました。

2022-11-21 00:03 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/service/MovieServiceImpl.java
> +        return Optional.ofNullable(movieMapper.findById(id).orElseThrow(() -> new ResourceNotFoundException("resource not found")));
業務処理の方に例外処理をさせる様に変更しました。

2022-11-21 13:38 UTC, yoshi-koyama commented on build.gradle
>      runtimeOnly 'com.mysql:mysql-connector-j'
こちらインデントが直っていないようです！

2022-11-21 13:38 UTC, yoshi-koyama commented on src/main/java/net/raisetech/raisetechtask9/entity/Movie.java
>      }
ここも
published_year
↓
publishedYear
です。

2022-11-21 13:38 UTC, yoshi-koyama commented on src/main/java/net/raisetech/raisetechtask9/service/MovieServiceImpl.java
> +        return Optional.ofNullable(movieMapper.findById(id).orElseThrow(() -> new ResourceNotFoundException("resource not found")));
movieMapper.findById(id)の戻り値はOptionalなのでOptional.ofNullableは不要ですね。
```suggestion
        return movieMapper.findById(id).orElseThrow(() -> new ResourceNotFoundException("resource not found"));
```

2022-11-21 14:42 UTC, takurouishihara reviewed
3つの修正が終了しました。ご確認お願いします。

2022-11-21 14:42 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/service/MovieServiceImpl.java
> -        return Optional.ofNullable(movieMapper.findById(id).orElseThrow(() -> new ResourceNotFoundException("resource not found")));
MovieMapperの方で使っているため、不要な Optionalを修正しました。

2022-11-21 14:42 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/entity/Movie.java
> +        return publishedYear;
こちらも、Javaの命令規則に従い、変更しました。

2022-11-21 14:42 UTC, takurouishihara commented on src/main/java/net/raisetech/raisetechtask9/controller/MovieController.java
>  import net.raisetech.raisetechtask9.entity.Movie;
インデントの調整がこれでおそらく出来たと思います。やったつもりになっていましたが、出来てなかったようですいませんでした。

2022-11-21 14:48 UTC, yoshi-koyama approved these changes

2022-11-21 15:17 UTC, merged